apiVersion: v1
kind: Service
metadata:
  name: miweb-service
spec:
  type: NodePort
  selector:
    app: miweb
  ports:
    - port: 80        # Puerto del Service dentro del cluster
      targetPort: 80  # Puerto del contenedor (NGINX)
      nodePort: 30080 # Puerto expuesto en el nodo (Minikube)